### PR TITLE
fix minitest-handler from kitchen runlist.…

### PR DESCRIPTION
**Pull request by slyness**
see [TESTING](../TESTING.md) for updated testing information

### CODE REVIEW

**Comment by cwjohnston** [comment]
Given that the existing minitest specs provide better coverage than what we currently have with ChefSpec, I think we should try to retain these tests until we can enhance the ChefSpec and add ServerSpec for integration tests. TESTING.md still applies.

From my testing locally it seems that our usage of minitest-handler breaks under Chef ~> 12.4; specifying the following in .kitchen.yml gets those tests working again:

```
provisioner:
  require_chef_omnibus: 12.3
```

**Comment by slyness** [comment]
Thanks Camero. I'll give that a try.

**Comment by slyness** [comment]
No longer need to make changes. Corrected local testing environment by removing an old crusty Cheffile.lock and converging again.

**Pull request closed without merging**
