### PR TITLE
Add PostgreSQL 9.4 download links for PGDG repository

### PR DESCRIPTION
**Pull request by GUI**
This sets up the default attributes for yum-based systems using the PGDG repository with the 9.4 download URLs.

### CODE REVIEW

**Comment by ajsharp** [comment]
+1

**Comment by jarosser06** [comment]
:+1:

**Comment by samnrubin** [comment]
:+1: getting 9.4 on rhel6 would be nice

**Comment by slyness** [comment]
These seem to all be covered currently. I'm going to close this. Thank you for contributing.

**Pull request closed without merging**
